### PR TITLE
Inconsistent output

### PR DESCRIPTION
**Pull request by martinezmatias**
IMHO, the output of the first test case (i.e., first line) has a different format than the remaining test cases. The output should be a *List of Lists*, instead of *List of numbers* (i.e., [1]).

### CODE REVIEW

**Comment by jkoppel** [comment]
Does it continue to work after this change?

**Comment by martinezmatias** [comment]
I develop new test cases and all of them pass.

Note that the Java version has as signature:

 ``public static ArrayList<ArrayList<Integer>> pascal(int n) {``

and the first statements are:
     `` ArrayList<ArrayList<Integer>> rows = new ArrayList<ArrayList<Integer>>();

        ArrayList<Integer> init = new ArrayList<Integer>();

        init.add(1);

        rows.add(init);
``

and at the end 
``
return rows;
``

So, if we transform the output from Java to JSON it would be: [[1]]

**Comment by SophieHYe** [comment]
Hi Martias,

Yes, you are right with the inconsistence JSON problem.  Actually, when I use a test generator to generate Junit tests, I have already correct them in my forked repo. See:https://github.com/SophieHYe/QuixBugs/blob/master/java_testcases/junit/PASCAL_TEST.java 

It was my problem that I haven't make a pull request to correct it to the main repo. I will sync the repo by today.

**Comment by drrckln** [comment]
I think this is fine, but I'd like someone to check that this test case ([[1]]) still works with the reference Python program. If it doesn't, it raises the question of whether the Python and Java versions are identical or not. We can change the reference Python program, but Python and Java implementations should be consistent on both input and output.

**Comment by drrckln** [comment]
Oh! I just took a look. This is obviously correct. Merging.

**Pull request merged**
