### PR TITLE
Fixed java programs compilation errors and added Junit generator

### PR DESCRIPTION
**Pull request by SophieHYe**
Fixed java programs compilation errors include:
-Corrected package name and class name to fix compilation error
-Corrected useless return statement that cause a compilation error
-Added shortest_paths method to fix compilation error in JavaTest

### CODE REVIEW

**Comment by drrckln** [comment]
I haven't looked at this in-depth yet, but there is a question of whether to fix the compilation errors or keep the previous priority on having Java and Python programs semantically the same.

**Comment by jkoppel** [comment]
Thanks for your contribution, Sophie.

@drrckln Some program repair tools need dynamic analysis, and hence need to be able to run the original buggy programs. We hence need them all to compile.

I ready through the commits in moderate detail. The first four commits seem reasonable.

Fifth commit: @SophieHYe Could you explain your modifications to the shortest paths program?

Sixth commit: The JunitTestGenerator looks unfinished; should not be in this PR.

**Comment by jkoppel** [comment]
Nice work! I see it's not done, but it looks fine so far.

Feel free to ignore all my comments on code quality. The quality of this code doesn't matter, but I have a code-quality critic that I can't turn off.

**Comment by SophieHYe** [comment]
Hi jkoppel,
Thanks a lot for your reviewing my PR and those kindly advise on my work. I appreciate it a lot. I just finished the function of Junit testcase generator and I was thinking to refine them in the next commit (probably tmr) . Basically the adding files and generating files are under folder junit_testcases, there is no configs on the original version. How about we can review my next commit and see what we can contribute to the Quixbugs :)

**Comment by SophieHYe** [comment]
Hey,

I think my part of Junit testcases generator is done. Could you please review and comment on it?

For your previous questions:
-but there is a question of whether to fix the compilation errors or keep the previous priority on having Java and Python programs semantically the same.

No worries. The current changes still keep Java and Python programs functionally the same and they still expose the same bugs. But we need all java programs complied successfully before we can try to adapt our repair tool on Quixbugs.

-Fifth commit: Could you explain your modifications to the shortest paths program?
I didn't modified the original shortest path program but rewrote one more method for it to accept different parameters as input. As in another JavaTest.java file which has compilation error because it calls shortest path method with illegal input parameters. As I see, we already have Junit tests for the java programs, this JavaTest file is not that important. Let me know if you have different opinion on this.

-String append not robust for path joining
 Yep, thanks for sharing. I used path joining instead :)

**Comment by monperrus** [comment]
> @drrckln Some program repair tools need dynamic analysis, and hence need to be able to run the original buggy programs. We hence need them all to compile.

Yes, that's exactly our motivation.

**Comment by jkoppel** [comment]
Reviewed in less detail than the first batch of commits. No issues jumped out.

Good job Sophie!

**Pull request merged**
