### PR TITLE
Update Gradle tasks

### PR DESCRIPTION
**Pull request by h4iku**
This PR extends the Gradle support of the repository to be able to run JUnit tests on both buggy and correct Java programs.

- `gradle test`: Runs JUnit tests on buggy programs.
- `gradle crtTest`: Runs JUnit tests on correct programs.

It is possible to run tests for a single program with `--tests` option:

```bash
$ gradle test --tests KNAPSACK_TEST

> Task :test

java_testcases.junit.KNAPSACK_TEST > test_1 FAILED
    java.lang.AssertionError at KNAPSACK_TEST.java:14

java_testcases.junit.KNAPSACK_TEST > test_3 FAILED
    java.lang.AssertionError at KNAPSACK_TEST.java:26

java_testcases.junit.KNAPSACK_TEST > test_4 FAILED
    java.lang.AssertionError at KNAPSACK_TEST.java:32

java_testcases.junit.KNAPSACK_TEST > test_5 FAILED
    java.lang.AssertionError at KNAPSACK_TEST.java:38

java_testcases.junit.KNAPSACK_TEST > test_6 FAILED
    java.lang.AssertionError at KNAPSACK_TEST.java:44

java_testcases.junit.KNAPSACK_TEST > test_7 FAILED
    java.lang.AssertionError at KNAPSACK_TEST.java:50

10 tests completed, 6 failed
```

```bash
$ gradle crtTest --tests KNAPSACK_TEST

BUILD SUCCESSFUL in 4s
```

I don't know if it's better to use `gradle test` for buggy programs or correct programs. Like pytest, the default is on buggy ones, and I created a new task for the correct ones. I thought people work on buggy programs to propose fixes and use the default command more.

I also added the directories that Gradle generates to the `.gitignore` file.

### CODE REVIEW

**Comment by drrckln** [comment]
I think `gradle test` for buggy programs makes sense. As the intent is for the buggy programs to be used as inputs for program repair (correct programs essentially for reference).. the testing capabilities mostly serve to provide human insight into how the buggy programs interact with the input/output pairs as well as sanity checks. At least that's my current thoughts.

**Comment by drrckln** [comment]
Looks good to me. @h4iku, please add gradle to the documentation, please :)

**Review by drrckln — CHANGES_REQUESTED** [review]
just needs documentation on usage

**Comment by h4iku** [comment]
I combined the documentation of TestGenerator and JUnit tests with Gradle usage because they were related and added them as a subsection.

**Review by drrckln — APPROVED** [review]

**Comment by drrckln** [comment]
Thanks, @h4iku!

**Pull request merged**
