### PR TITLE
Add pytest files for the Python version

### PR DESCRIPTION
**Pull request by h4iku**
Java version has its JUnit tests, so I thought the Python version might also benefit from pytest tests. I have put the tests under the `python_testcases` directory. To run them, you need first to install `pytest` using `pip` and then, from the root of the repository, call `pytest` to run tests for a single program or target the whole directory to run every test inside it.

```bash
pip install pytest
pytest python_testcases/test_quicksort.py
# Or
pytest python_testcases
```

Tests work for both buggy and correct versions of programs. The default test calls the buggy version, but there is a custom `--correct` flag that using it uses the correct version of a program.

```bash
pytest --correct python_testcases
```

Most of the tests run fast and finish in less than a second on my computer, but two tests are slow. The first one is the last test case of the `knapsack` program, which takes about four minutes to pass. The second one is the fourth test case of the `levenshtein` program that I let run for about half an hour, and it didn't finish, so I don't know how long it needs to pass. The default behavior skips both these tests. For the `knapsack` test case, using the `--runslow` pytest option will include it in the running tests. However, the `levenshtein` test case is always skipped since it is ignored by the [JUnit tests](https://github.com/jkoppel/QuixBugs/blob/7075c51cbb52058c37033f729c795aada5f6391c/java_testcases/junit/LEVENSHTEIN_TEST.java#L23-L28) as well.

```bash
$ pytest --correct --runslow python_testcases/test_knapsack.py

collected 10 items
python_testcases/test_knapsack.py ..........     [100%]

========== 10 passed in 240.97s (0:04:00) ========== 
```

```bash
$ pytest --correct python_testcases/test_knapsack.py

collected 10 items
python_testcases/test_knapsack.py ..........     [100%]

========== 9 passed, 1 skipped in 0.08s ========== 
```

Some tests, such as the `bitcount` ones, need a timeout. `pytest` itself doesn't have a timeout mechanism, but there is a [`pytest-timeout`](https://github.com/pytest-dev/pytest-timeout) plugin for it. I didn't hard code timeout values since I think different use cases have different needs, and `pytest-timeout` has some caveats. For example, on Windows, it can only use a thread method to timeout tests, and when a test times out, it terminates the whole program's process and doesn't continue running the remaining tests. On systems that support signals, it uses the signal method and doesn't have this problem. But people generally don't have to decorate tests to use a timeout. Installing `pytest-timeout` adds additional options to the `pytest` CLI so, for example, they can timeout `bitcount` tests after five seconds like this:

```bash
pip install pytest-timeout
pytest --timeout=5 python_testcases/test_bitcount.py
```

There is also a [`pytest-xdist`](https://github.com/pytest-dev/pytest-xdist) plugin that runs tests in parallel and can be used similarly to the timeout plugin.

Additionally, I changed some inconsistent JSON test cases so that they all have a list as input.

Let me know what you think.

### CODE REVIEW

**Review by drrckln — COMMENTED** [review]
Looks very nice. Going to check that changing the JSON inconsistencies doesn't screw with the Java versions.

**Comment by drrckln** [comment]
JSON list as input will not be a problem.

**Comment by drrckln** [comment]
Seems this will require a rethink of the utility of tester.py @h4iku in the meantime, can you add this explanation of the pytest usage to the README?

**Comment by h4iku** [comment]
Added the pytest usage explanation as a subsection under "Installation & Usage".

**Review by drrckln — APPROVED** [review]

**Pull request merged**
