### PR TITLE
new correct version of Powerset

### PR DESCRIPTION
**Pull request by martinezmatias**
The previous correct version fails for some inputs. I compared with that one from python and change it according.

### CODE REVIEW

**Comment by jkoppel** [comment]
@drrckln  What happened here?

**Comment by drrckln** [comment]
We didn't supply any correct Java programs originally, so I would guess the contributed correct Java program was mistranslated.

**Comment by martinezmatias** [comment]
Yes, the bugs in the corrected version was due to a different semantic of the *add* operator of python and ArrayDeque.

**Comment by martinezmatias** [comment]
The bug in the *buggy* java version is in the combination of the element *first* with each list from  rest_subsets.
The patch is: 
 			for (ArrayList subset : rest_subsets) {
 -                             to_add.addAll(subset);    
 +				ArrayList r = new ArrayList();
 +				r.add(first);
 +				r.addAll(subset);
 +				to_add.add(r);

Note that those changes do not have any relation with those changes that repair the original problem.

**Comment by SophieHYe** [comment]
Hi Martias,

Thanks very much for your patch.  You are completed correct with it.
I did not consider well with this case.  
Also, I have some files in my local that have not been submitted and send a pull request yet. It is very helpful to have your support in the benchmark setup.

**Comment by drrckln** [comment]
@martinezmatias 

Thanks for the work! I am happy to merge this, but please fix the spacing first. I've decided that we should adhere to the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html), so that's 2-space indentation.

**Comment by drrckln** [comment]
Actually, forget the spacing. I've added that as an issue, and we can fix that for the whole repo later.

**Pull request merged**
