### PR TITLE
Fix inconsistent buggy and correct source files

### PR DESCRIPTION
**Pull request by h4iku**
This PR makes buggy and correct source files of `DEPTH_FIRST_SEARCH`, `SHORTEST_PATH_LENGTH`, and `SQRT` consistent. 

The method declaration in the correct version of `DEPTH_FIRST_SEARCH` and `SHORTEST_PATH_LENGTH` uses `static` while the buggy version doesn't. The buggy version of `SQRT` uses `f` instead of `d`, which is used in the correct version and is not part of the bug.

Apart from consistency, this also helps to get nicer diffs between buggy and correct source files.

I also recompiled modified source files using Java 8 and added their class files.

### CODE REVIEW

**Comment by jkoppel** [comment]
LGTM. @drrckln  Please comment on what effect you think the changes here would have on the tests.

**Comment by drrckln** [comment]
All 3 look good to me as well. Reviewed the relevant node-based tests in java_testcases/ and they should be unaffected -- the tests still (unnecessarily) instantiate an object, but that's not affecting return values.

I think it'd make sense to update the DEPTH_FIRST_SEARCH_TEST and SHORTEST_PATH_LENGTH_TEST files to not instantiate an objject, in this PR.

**Comment by h4iku** [comment]
I updated these test files to not instantiate an object. There are other test files that instantiate objects as well. I will fix them in a separate PR.

**Comment by drrckln** [comment]
Thank you, @h4iku!

**Pull request merged**
