### PR TITLE
Bugfix on correct version of SHUNTING_YARD

### PR DESCRIPTION
**Pull request by martinezmatias**
Bugfix on Correct Version of SHUNTING_YARD: replacing wrong method invocation (add) in queue (it adds at the end). Replaced by push (it
adds at the beginning)

### CODE REVIEW

**Comment by jkoppel** [comment]
@drrckln @SophieHYe  How did this happen?

**Comment by drrckln** [comment]
This commit is hard to read because it seems spaces has been changed to tabs, so it's hard to read the diff. (What's the standard in Java? I'm guessing we used 4-space indentation originally.)

Also, there weren't correct versions of the Java programs. How were they created? Copy the buggy version and fix? I would be worried that this is also an issue in the incorrect Java version.

**Comment by martinezmatias** [comment]
Sorry for the indentation problem: I use that one defined by default by Eclipse IDE. 
I discovered the issue by running a new set of test cases (using my generation scripts) and running them over the correct versions. There, I found that the output of SHUNTING_YARD was always incorrect, so I debug it and compared with the correct version from Python that you provide. So, I found the problem.

**Comment by drrckln** [comment]
Well, we may have used non-standard indentation in the first place, so I'd like to know if there is a standard and switch to that. Otherwise it seems like this is a go for merging, since you've compared it to the reference correct Python implementations.

Are your pull requests all the issues that you discovered by running new test cases?

**Comment by martinezmatias** [comment]
> we may have used non-standard indentation in the first place,
Yes, the Eclipse built-in config uses Tabs, each of 4 spaces.
 
> since you've compared it to the reference correct Python implementations
The patch is: 
34 -                opstack.add(token);
34 +	      opstack.push(token);
Note that the Java implementation uses different data structures, whereas that one from python uses one one (list).

> Are your pull requests all the issues that you discovered by running new test cases?
Yes. With the new test cases: a) all buggy program fails in at least one test, b) all correct programs pass. Previous test cases fail on other corrects (i.e., on the correct ones, excluding those wrong previously discussed). Note that I had to ignore only one test: test #4 from LevenshteinTest  takes so long that I decided to annotate it with Ignore annotation.

**Comment by SophieHYe** [comment]
@jkoppel @drrckln @martinezmatias 
Hi all, I have discussed with Matias. These three PR Matias just raised completely make sense. Thanks a lot for his correct patches for these two programs that I failed to notice the error.

We have analyze the 33 correct Java programs that I sent Pull Requests before, except for these two programs, other 31 programs are correct.  And I will do another PR for adding the rest 7 correct programs. I will check the correctness with Matias before I do PR.

We are interested in the automatic repair in Java and we are motivated to setup QuixBugs as a great benchmark for the following researchers. In the meantime, I am very sorry for the mistakes I made in my PR.

I would like to share our following plan with you:

First, we will make a PR to correct  the JSON errors.

Second, we will make a PR to update our existing Junit test generator. Matias did a great work on this, I will integrate it to the existing one but makes it simpler. In the meantime, we will resubmit our new generated tests. But the correctness of  second step is completely based on the first step to make sure the Json is correct.

Much appreciate for your understanding and I look forward to work together with you on automatic repair field :)

**Comment by drrckln** [comment]
@SophieHYe @martinezmatias 

Could one of you open an issue and put the plan and all updates inside? It'll be easier to coordinate this way.

**Pull request merged**
